# Generated by Django 5.0.2 on 2025-01-07 21:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_country', '0002_remove_country_public_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='country',
            name='created',
        ),
        migrations.RemoveField(
            model_name='country',
            name='updated',
        ),
    ]
