# Generated by Django 5.0.2 on 2025-01-06 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_industry', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supersector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supersectors', to='apps_industry.industry')),
            ],
        ),
    ]
