version: '3.8'

services:
  nginx:
    container_name: intracen
    restart: always
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - uploads_volume:/app/uploads
    ports:
      - "80:80"
    depends_on:
      - api # waiting for the Django api to start the service

  db:
    container_name: intracen_db
    image: postgres:14.3-alpine
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  api:
    container_name: intracen_api
    build: . # where to find the Dockerfile, in this case in the same directory
    restart: always
    env_file:
      - .env
    ports:
      - "8000:8000"
    command: sh -c "python manage.py migrate --no-input && gunicorn intracen.wsgi:application --bind 0.0.0.0:8000"
    volumes:
      - .:/app
      - uploads_volume:/app/uploads
    depends_on:
      - db

volumes:
  uploads_volume:
  postgres_data:



