# Generated by Django 5.0.2 on 2024-07-20 21:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_country', '0001_initial'),
        ('apps_industry', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('postal_code', models.CharField(blank=True, default='None', max_length=20, null=True)),
                ('city', models.CharField(blank=True, default='None', max_length=50, null=True)),
                ('year_establishment', models.IntegerField(default=1950)),
                ('year_first_expo', models.IntegerField(default=1950)),
                ('bussines_description', models.TextField(blank=True, default='None', max_length=1000, null=True)),
                ('comments', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('eva_made', models.IntegerField(default=0)),
                ('eva_progress', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_country.country')),
                ('subsector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_industry.subsector')),
                ('user_creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'apps.companies',
                'ordering': ('name', 'user_creator', 'country', 'subsector', 'eva_made', 'created'),
            },
        ),
    ]
