# Generated by Django 5.0.2 on 2025-01-06 22:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_country', '0001_initial'),
        ('apps_subsector', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=150)),
                ('address', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('postal_code', models.CharField(blank=True, default='None', max_length=20, null=True)),
                ('city', models.CharField(blank=True, default='None', max_length=50, null=True)),
                ('year_establishment', models.IntegerField(default=0)),
                ('year_first_expo', models.IntegerField(default=0)),
                ('business_description', models.TextField(blank=True, default='None', max_length=1000, null=True)),
                ('comments', models.CharField(blank=True, default='None', max_length=250, null=True)),
                ('eva_made', models.IntegerField(default=0)),
                ('eva_progress', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_country.country')),
                ('subsector', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_subsector.subsector')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'apps.companies',
                'ordering': ('name', 'user_creator', 'country', 'subsector', 'eva_made', 'created'),
            },
        ),
    ]
