# Generated by Django 5.0.2 on 2024-07-30 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_companies', '0003_rename_bussines_description_company_business_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='year_establishment',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='company',
            name='year_first_expo',
            field=models.IntegerField(default=0),
        ),
    ]
