# Generated by Django 5.0.2 on 2024-02-22 22:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0002_alter_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
