# Generated by Django 5.0.2 on 2024-02-24 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0003_remove_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, default='Mickey', max_length=255, unique=True),
        ),
    ]
