# Generated by Django 5.0.2 on 2024-02-24 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0005_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
