# Generated by Django 5.0.2 on 2024-05-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_user', '0010_user_created_user_updated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('1', 'ADMIN'), ('2', 'SUPER_USER'), ('3', 'GENERAL_USER')], default='3', max_length=12),
        ),
    ]
