# Generated by Django 5.0.2 on 2024-02-27 13:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_element', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='element_type',
            field=models.CharField(choices=[(1, 'competences'), (2, 'capabilities'), (3, 'processes')], verbose_name='Element Type'),
        ),
        migrations.AlterField(
            model_name='element',
            name='user_creator',
            field=models.ForeignKey(default=12, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
