# Generated by Django 5.0.2 on 2024-03-07 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_element', '0005_alter_element_element_type_alter_element_letter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='element',
            options={'ordering': ('element_type', 'letter', 'name', 'created'), 'verbose_name': 'Element', 'verbose_name_plural': 'Elements'},
        ),
    ]
