# Generated by Django 5.0.2 on 2024-03-20 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_element', '0006_alter_element_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='element',
            name='assess_five',
            field=models.TextField(blank=True, default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='element',
            name='assess_four',
            field=models.TextField(blank=True, default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='element',
            name='assess_one',
            field=models.TextField(blank=True, default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='element',
            name='assess_three',
            field=models.TextField(blank=True, default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='element',
            name='assess_two',
            field=models.TextField(blank=True, default='None', max_length=1000),
        ),
        migrations.AlterField(
            model_name='element',
            name='definitions',
            field=models.TextField(blank=True, default='None', max_length=2000, verbose_name='Definitions'),
        ),
        migrations.AlterField(
            model_name='element',
            name='questions',
            field=models.TextField(blank=True, default='None', max_length=3000, verbose_name='Sample questions'),
        ),
        migrations.AlterField(
            model_name='element',
            name='symptoms',
            field=models.TextField(blank=True, default='None', max_length=3000, verbose_name='Symptoms'),
        ),
    ]
