# Generated by Django 5.0.2 on 2025-01-06 22:10

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Relation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Relation name')),
                ('total_elements', models.IntegerField(default=0)),
                ('competences', models.SmallIntegerField(default=0, verbose_name='Competences')),
                ('capabilities', models.SmallIntegerField(default=0, verbose_name='Capabilities')),
                ('processes', models.IntegerField(default=0, verbose_name='Processes')),
                ('eva_made', models.IntegerField(default=0, verbose_name='Evaluations made')),
                ('eva_progress', models.IntegerField(default=0, verbose_name='Evaluations in progress')),
                ('comments', models.CharField(default='None', max_length=255, verbose_name='Comments')),
                ('status', models.BooleanField(default=0)),
            ],
            options={
                'verbose_name': 'Relation',
                'verbose_name_plural': 'Relations',
                'db_table': 'apps.relation',
                'ordering': ('name', 'eva_made', 'eva_progress', 'status'),
            },
        ),
        migrations.CreateModel(
            name='RelationTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('capability_number', models.CharField()),
                ('process_number', models.CharField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('element_type', models.SmallIntegerField()),
                ('relation_letter', models.SmallIntegerField()),
                ('relation_letter_display', models.CharField()),
                ('related_capability', models.IntegerField(blank=True, null=True)),
                ('related_competence', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'apps.relation_tree',
                'ordering': ('relation', 'order'),
            },
        ),
    ]
