# Generated by Django 5.0.2 on 2024-07-04 13:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_relations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='relation',
            name='user_creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterModelTable(
            name='relation',
            table='apps.relation',
        ),
        migrations.CreateModel(
            name='RelationTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('capability_number', models.SmallIntegerField()),
                ('process_number', models.SmallIntegerField()),
                ('percentage', models.DecimalField(decimal_places=2, max_digits=3)),
                ('element_type', models.SmallIntegerField()),
                ('relation_letter', models.SmallIntegerField()),
                ('relation_letter_display', models.CharField()),
                ('element_public_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_relations.relation')),
            ],
            options={
                'db_table': 'apps.relation_tree',
            },
        ),
    ]
