# Generated by Django 5.0.2 on 2024-07-08 12:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_element', '0010_alter_element_letter'),
        ('apps_relations', '0006_alter_relation_user_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtree',
            name='relation_public_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='apps_relations.relation'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='relationtree',
            name='element_public_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_element.element'),
        ),
    ]
