# Generated by Django 5.0.2 on 2024-07-08 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_relations', '0007_relationtree_relation_public_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='relationtree',
            old_name='element_public_id',
            new_name='element',
        ),
        migrations.RenameField(
            model_name='relationtree',
            old_name='relation_public_id',
            new_name='relation',
        ),
    ]
