# Generated by Django 5.0.2 on 2024-07-08 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_relations', '0008_rename_element_public_id_relationtree_element_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationtree',
            name='percentage',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
