# Generated by Django 5.0.2 on 2024-07-08 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_relations', '0009_alter_relationtree_percentage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationtree',
            name='capability_number',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='relationtree',
            name='process_number',
            field=models.CharField(),
        ),
    ]
