# Generated by Django 5.0.2 on 2024-07-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_relations', '0010_alter_relationtree_capability_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='eva_made',
            field=models.IntegerField(default=0, verbose_name='Evaluations made'),
        ),
    ]
