# Generated by Django 5.0.2 on 2024-07-13 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_relations', '0011_alter_relation_eva_made'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationtree',
            name='relation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_tree', to='apps_relations.relation'),
        ),
    ]
