# Generated by Django 5.0.2 on 2024-07-25 17:43

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_relations', '0012_alter_relationtree_relation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='public_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
