# Generated by Django 5.0.2 on 2024-08-07 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_relations', '0013_alter_relation_public_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='relationtree',
            options={'ordering': ('relation', 'order')},
        ),
    ]
