# Generated by Django 5.0.2 on 2024-08-15 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_relations', '0015_alter_relation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relation',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Relation name'),
        ),
    ]
