# Generated by Django 5.0.2 on 2024-09-20 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_element', '0011_alter_element_public_id'),
        ('apps_relations', '0016_alter_relation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationtree',
            name='element',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element', to='apps_element.element'),
        ),
    ]
