# Generated by Django 5.0.2 on 2024-10-05 12:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_element', '0011_alter_element_public_id'),
        ('apps_relations', '0017_alter_relationtree_element'),
    ]

    operations = [
        migrations.AddField(
            model_name='relationtree',
            name='related_capability',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_capability', to='apps_element.element'),
        ),
        migrations.AddField(
            model_name='relationtree',
            name='related_competence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='related_competence', to='apps_element.element'),
        ),
    ]
