# Generated by Django 5.0.2 on 2024-10-05 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_relations', '0018_relationtree_related_capability_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationtree',
            name='related_capability',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='relationtree',
            name='related_competence',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
