# Generated by Django 5.0.2 on 2024-08-08 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps_companies', '0004_alter_company_year_establishment_and_more'),
        ('apps_element', '0011_alter_element_public_id'),
        ('apps_relations', '0014_alter_relationtree_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('processes_evaluated', models.IntegerField(default=0)),
                ('finalized', models.BooleanField(default=0)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_companies.company')),
                ('creator_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='creator_user', to=settings.AUTH_USER_MODEL)),
                ('end_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='end_user', to=settings.AUTH_USER_MODEL)),
                ('relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_relations.relation')),
            ],
            options={
                'ordering': ('company', 'relation'),
            },
        ),
        migrations.CreateModel(
            name='ElementScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(default=0)),
                ('form_number', models.IntegerField(default=0)),
                ('order', models.SmallIntegerField(default=0)),
                ('score_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('score_final', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_element.element')),
                ('relation_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_relations.relationtree')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_evaluations.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='DataModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('years_exporting', models.IntegerField(default=0)),
                ('plans_to_export', models.SmallIntegerField(default=0)),
                ('export_variation', models.IntegerField(default=0)),
                ('foreign_investment', models.BooleanField(default=0)),
                ('average_years', models.IntegerField(default=0)),
                ('top_or_middle', models.IntegerField(default=0)),
                ('women_employed', models.IntegerField(default=0)),
                ('women_top_or_middle', models.IntegerField(default=0)),
                ('ceo_title', models.SmallIntegerField(default=1)),
                ('given_name', models.CharField(default='Empty', max_length=100)),
                ('family_name', models.CharField(default='Empty', max_length=100)),
                ('gender', models.SmallIntegerField(default=1)),
                ('telephone', models.CharField(default='Empty', max_length=20)),
                ('email', models.CharField(default='Empty', max_length=100)),
                ('bussines_position', models.CharField(default='Empty', max_length=100)),
                ('years_in_the_post', models.IntegerField(default=0)),
                ('comments', models.TextField(default='Empty', max_length=255)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_evaluations.evaluation')),
            ],
        ),
        migrations.CreateModel(
            name='MainProducts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.CharField(max_length=30)),
                ('percentage', models.IntegerField(default=0)),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_evaluations.evaluation')),
            ],
        ),
    ]
