# Generated by Django 5.0.2 on 2025-01-08 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_evaluations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationscore',
            name='element_type',
            field=models.IntegerField(default=1),
        ),
    ]
