# Generated by Django 5.0.2 on 2024-08-12 12:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_element', '0011_alter_element_public_id'),
        ('apps_evaluations', '0001_initial'),
        ('apps_relations', '0014_alter_relationtree_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_score', models.IntegerField(default=0)),
                ('form_number', models.IntegerField(default=0)),
                ('order', models.SmallIntegerField(default=0)),
                ('final_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percentage_score', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('element', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='element_related', to='apps_element.element')),
                ('evaluation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apps_evaluations.evaluation')),
                ('relation_tree', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_tree_related', to='apps_relations.relationtree')),
            ],
        ),
        migrations.DeleteModel(
            name='ElementScore',
        ),
    ]
