# Generated by Django 5.0.2 on 2024-08-29 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_evaluations', '0002_evaluationscore_delete_elementscore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datamodel',
            old_name='bussines_position',
            new_name='business_position',
        ),
    ]
