# Generated by Django 5.0.2 on 2025-01-08 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_evaluations', '0002_evaluationscore_element_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evaluationscore',
            name='element_type',
            field=models.IntegerField(),
        ),
    ]
