# Generated by Django 5.0.2 on 2024-08-29 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_evaluations', '0003_rename_bussines_position_datamodel_business_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datamodel',
            name='plans_to_export',
            field=models.SmallIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datamodel',
            name='plans_to_export',
            field=models.BooleanField(default=0),
        ),        
    ]
