# Generated by Django 5.0.2 on 2024-10-07 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_evaluations', '0010_evaluationcapabilityscore_evaluationcompetencescore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluationcapabilityscore',
            name='created',
        ),
        migrations.RemoveField(
            model_name='evaluationcapabilityscore',
            name='public_id',
        ),
        migrations.RemoveField(
            model_name='evaluationcapabilityscore',
            name='updated',
        ),
    ]
