# Generated by Django 5.0.2 on 2024-10-07 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_evaluations', '0011_remove_evaluationcapabilityscore_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluationcapabilityscore',
            name='count_competence',
            field=models.IntegerField(default=0),
        ),
    ]
