# Generated by Django 5.0.2 on 2024-10-08 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_evaluations', '0013_alter_evaluationcapabilityscore_count_competence'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evaluationcapabilityscore',
            old_name='count_competence',
            new_name='competence_weight',
        ),
    ]
