# Generated by Django 5.0.2 on 2024-11-01 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps_logs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='date',
        ),
    ]
