# Generated by Django 5.0.2 on 2024-11-01 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_logs', '0002_remove_logs_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logs',
            name='location',
        ),
        migrations.AddField(
            model_name='logs',
            name='location_city',
            field=models.CharField(default='None', max_length=200),
        ),
        migrations.AddField(
            model_name='logs',
            name='location_country',
            field=models.CharField(default='None', max_length=200),
        ),
    ]
