# Generated by Django 5.0.2 on 2024-07-25 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps_industry', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sector',
            name='supersector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sectors', to='apps_industry.supersector'),
        ),
        migrations.AlterField(
            model_name='subsector',
            name='sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subsectors', to='apps_industry.sector'),
        ),
        migrations.AlterField(
            model_name='supersector',
            name='industry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supersectors', to='apps_industry.industry'),
        ),
    ]
