name: Build, Test and Deploy Intracen

on:
    push:
        branches: [ main ]

jobs:
    build-test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Injecting env vars
              run: echo "SECRET_KEY=django-insecure-7w1%wxfq2rrbqycal^qprwsi*d)dfqp(gdyi+b6jejt3_fyh&6
                DATABASE_NAME=intracen
                DATABASE_USER=admin
                DATABASE_PASSWORD=admin
                DATABASE_HOST=intracen_db
                DATABASE_PORT=5432
                POSTGRES_USER=admin
                POSTGRES_PASSWORD=admin
                POSTGRES_DB=intracen
                ENV=DEV
                DJANGO_ALLOWED_HOSTS=127.0.0.1,localhost" >> .env
            - name: Building containers
              run: docker-compose up -d --build

    deploy:
        name: Deploying on EC" via SSH
        if: ${{github.event_name == 'push'}}
        needs: [build-test]
        runs-on: ubuntu-latest
        steps:
        - name: Deploying application on EC2
          uses: appleboy/ssh-action@master
          with:
            host: ${{secrets.SSH_EC2_IP}}
            username: ${{secrets.SSH_EC2_USER}}
            key: ${{secrets.SSH_PRIVATE_KEY}}
            passphrase: ${{secrets.SSH_PASSPHRASE}}
            script: |
                cd drf-react
                ./docker-ec2-deploy.sh




